# Generated by Django 4.0.4 on 2022-05-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField()),
                ('description', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inventory', models.CharField(max_length=255)),
            ],
        ),
    ]
