# Generated by Django 4.0.4 on 2022-05-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_quantiy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=225),
        ),
    ]
