# Generated by Django 4.0.4 on 2022-05-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_inventory_product_inventory_quantiy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='inventory_quantiy',
            new_name='inventory_quantity',
        ),
    ]
